"""empty message

<<<<<<<< HEAD:api/migrations/versions/0caac4859f43_.py
Revision ID: 0caac4859f43
Revises: 
Create Date: 2022-10-27 15:05:14.722775
========
Revision ID: e92f976c2188
Revises: 
Create Date: 2022-10-27 12:59:55.397934
>>>>>>>> f869b5337f555aaf88c42ef2e45c40cfed8006fb:api/migrations/versions/e92f976c2188_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:api/migrations/versions/0caac4859f43_.py
revision = '0caac4859f43'
========
revision = 'e92f976c2188'
>>>>>>>> f869b5337f555aaf88c42ef2e45c40cfed8006fb:api/migrations/versions/e92f976c2188_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profilename', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('public_id', sa.String(length=120), nullable=True),
    sa.Column('muni_firstname', sa.String(length=120), nullable=True),
    sa.Column('muni_lastname', sa.String(length=120), nullable=True),
    sa.Column('muni_email', sa.String(length=120), nullable=True),
    sa.Column('muni_phone', sa.String(length=10), nullable=True),
    sa.Column('muni_position', sa.String(length=120), nullable=True),
    sa.Column('municipality', sa.String(length=120), nullable=True),
    sa.Column('muni_password', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coordinates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.String(length=20), nullable=False),
    sa.Column('longitude', sa.String(length=20), nullable=True),
    sa.Column('imageurl', sa.String(length=20), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('galleries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('password', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('galleries')
    op.drop_table('coordinates')
    op.drop_table('users')
    op.drop_table('profile')
    # ### end Alembic commands ###
